---
abstract: 'handle and create CouchDB views in Perl'
author:
  - 'Hans Dieter Pearcey <hdp@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CouchDB-View
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dump::Streamer: 0
  JSON::XS: 0
version: 0.001
